AllCops:
  NewCops: 'enable'
  TargetRubyVersion: 2.5
  Exclude:
    - '*.gemspec'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 99

Style/Documentation:
  Enabled: false
