---
language: ruby
# cache: bundler
rvm:
  - 2.6.0
  - 2.5.0
before_install: gem install bundler -v 2.0.2
script:
  - bundle exec bundle-audit check --update
  - bundle exec rubocop
  - bundle exec rspec
